name: Mustang
maker: Ford
year: 2012
milage: 40,000
issues:
  - hood rdsDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: 
      SubnetIds:
        - subnet-id
    Tags:
      - Key: keyname
        Value: value